<?php

use Illuminate\Database\Seeder;
use App\Examen;
use App\ExamenValor;
use Faker\Factory as Faker;
     
class ExamenesTableSeeder extends Seeder {

    public function run()
    {
        $ex =  array(
                        "Glucosa",
                        "Glucosa pos pandrial",
                        "Triglicéridos",
                        "Colesterol",
                        "Colesterol HDL",
                        "Colesterol LDL",
                        "Creatinina",
                        "Acido Úrico",
                        "Nitrógeno Ureico",
                        "Urea",
                        "TGP / ALT",
                        "TGO / AST",
                        "Proteínas totales",
                        "Albumina",
                        "Globulina",
                        "Relación  A/G",
                        "Bilirrubina total",
                        "Bilirrubina directa",
                        "Creatinina fosfoquinasa",
                        "Fosfatasa alcalina",
                        "Fosfatasa alcalina ( Barry )",
                        "Fosfatasa acida",
                        "Proteína en orina 24/h",
                        "Sodio en sangre",
                        "Calcio en sangre",
                        "Potasio en sangre",
                        "Fosforo en sangre",
                        "Cloro en sangre",
                        "Hemoglobina glicosilada",
                        "Potasio en sangre – barry",
                        "Proteína en orina 24/h",
                        "Magnesio",
                        "Tolerancia a la glucosa  5/h ",
                        "Amilasa",
                        "Lipasa",
                        "PSA",
                        "Tiempo de protrombina  TP",
                        "T.de tromboplastina parcial TTp",
                        "Tiempo de trombina TT",
                        "Velocidad de eritrocediment",
                        "Tiempo de sangramiento",
                        "Tiempo de coagulación",
                        "T3, ( Triyodotironina )",
                        "T4, ( Tiroxina )",
                        "TSH",
                        "Estreptolicina o ( ASO )- ultra)",
                        "Estreptolicina o ( ASO ) barry",
                        "Alfa feto proteína ( AFP )",
                        "( En embarazó )",
                        "Proteína c reactiva (PCR) ultra",
                        "Proteína C reactiva (PCR) Barry",
                        "Factor reumatoideo",
                        "Microalbumina en orina",
                        "Anticuerpos para dengue IgM",
                        "Anticuerpos para dengue IgG",
                        "Antígenos febriles",
                        "Ca 19 – 9 Elisa ( Cuantitativa )",
                        "Toxoplasmosis IgG ( barry )",
                        "Toxoplasmosis IgM (barry )",
                        "Gama glutamil transferasa (GG)",
                        "Factor reumatoideo ( FR )",
                        "Prolactina",
                        "Insulina en ayunas",
                        "Anticoagulante lupico ",
                        "Cardiolipina  IgG",
                        "Cardiolipina  IgM",
                        "Fibrinogeno",
                        "Concentracion de crea",
                        "Depuracion de crea 24 /h",
                        "IgE, Total",
                        "Ac. Antinucleares latex  ( ANA )",
                        "Ac. Anticitrolinados IgG",
                        "Helicobacter pylori IgM, IgG.",
                        "Cortisol,  AM",
                        "Microalbumina ( Orina )",
                        "Hierro  serico",
                        "Alfafetoproteinas",
                        "Gonadotropina corionica cuant.",
                        "Peptido Natriuretico ( BNP )",
                        "Hb.Electroforesis"
                       );
            
        $v = array(
                    id =>  "1", nombre => "70 – 105 mg /dl",
                    id =>  "2", nombre => "Hasta 140 mg /dl ",
                    id =>  "3", nombre => "Hasta 150 mg /dl ",
                    id =>  "4", nombre => "Hasta 200 mg /dl",
                    id =>  "5", nombre => "No riesgo mayor de 60 mg /dl  ",
                    id =>  "5", nombre => "Riesgo menor de 35 mg /dl ",
                    id =>  "6", nombre => "Menor de 150 mg /dl ",
                    id =>  "7", nombre => "Hombres 0.7  - 1.3 mg /dl",
                    id =>  "7", nombre => "Mujeres 0.6 – 1.1",
                    id =>  "8", nombre => "2.4 – 7.0 mg /dl ",
                    id =>  "9", nombre => "8 – 23 mg /dl ",
                    id => "10", nombre => "17 – 49 mg /dl ",
                    id => "11", nombre => "Hombres menor de 40 UI",
                    id => "11", nombre => "Mujeres menor de 32 UI",
                    id => "12", nombre => "8 – 33 UI",
                    id => "13", nombre => "5.8 – 8.8 /dl",
                    id => "13", nombre => "Neonatos ",
                    id => "13", nombre => "Hasta 1 semana 4.4 – 7.14 6  g/dl",
                    id => "14", nombre => "3.4 – 5.0  g /dl",
                    id => "15", nombre => "2.6 – 3.1 g /dl",
                    id => "16", nombre => "1.1 – 3.1 g /dl ",
                    id => "17", nombre => "Hasta 1.20",
                    id => "18", nombre => "Hasta  0.50",
                    id => "19", nombre => "Hasta 170 U / L",
                    id => "20", nombre => "40 – 129 U/L",
                    id => "21", nombre => "Hombres < - 270 U/I",
                    id => "21", nombre => "Mujeres < - 240 U/I",
                    id => "22", nombre => "Hombres <  5.4 – U/L",
                    id => "22", nombre => "Mujeres <  4.2 – U/L",
                    id => "23", nombre => "10 – 150 mg / 24 horas",
                    id => "24", nombre => "General  135 – 155 mmol /L",
                    id => "25", nombre => "Recién nacido 8 – 13 mg /dl",
                    id => "25", nombre => "Niño 10 – 12 mg /dl ",
                    id => "25", nombre => "Adulto  8.5 – 10.5 mg /dl",
                    id => "26", nombre => "3.6 – 5.5 mmol /L",
                    id => "27", nombre => "Adultos 2.5 – 5.0 mg /dl",
                    id => "27", nombre => "Neonatos 5  - 9.6 mg /dl",
                    id => "27", nombre => "Niños hasta 1 año  5 – 10 mg /dl ",
                    id => "27", nombre => "Mayor de 60 años 3.4 – 6.2 mg /dl ",
                    id => "28", nombre => "95 – 115 mmol/L",
                    id => "29", nombre => "Paciente  no diabético 4.2 - 6.2%",
                    id => "29", nombre => "Buen control 5.5 – 6.8 %",
                    id => "29", nombre => "Control regular 6.8 – 7.6 %",
                    id => "29", nombre => "Control pobre mayor de > -7.6 %",
                    id => "30", nombre => "Suero 3.6 – 5.5 mmol/L",
                    id => "30", nombre => "Plasma 4.0 – 4.8 mmoI/L",
                    id => "31", nombre => "Menor de 100 mg /24horas",
                    id => "31", nombre => "M. embarazadas menor de 150 mg/24 h.",
                    id => "32", nombre => "General 1.6 – 2.5 mg /dl",
                    id => "33", nombre => "En ayunas  70 – 105 mg /dl ",
                    id => "33", nombre => "1- menor de 190 mg /dl ",
                    id => "33", nombre => "2- menor de 160 mg /dl ",
                    id => "33", nombre => "3- menor de 140 mg /dl ",
                    id => "33", nombre => "4- menor de 120 mg /dl",
                    id => "34", nombre => "Suero 25 – 125 U/L",
                    id => "34", nombre => "Orina 1 – 17 U/L",
                    id => "35", nombre => "Menor o igual  - 66 U/L ",
                    id => "36", nombre => "Normal o bajo riesgo 0 - 4 ng/mL",
                    id => "36", nombre => "Mediano riesgo 4-10 ng/mL",
                    id => "36", nombre => "Alto riesgo mayor. 10 ng/mL",
                    id => "37", nombre => "10 – 14 Segundos ( 10 – 16 segundos )",
                    id => "38", nombre => "20 – 35 Segundos ( 20 – 35 segundos )",
                    id => "38", nombre => "16  - 23 segundos ",
                    id => "39", nombre => "Mujeres 0 – 15 mm /h",
                    id => "39", nombre => "Hombres 0 – 7 mm /h",
                    id => "40", nombre => "1 – 4 minutos",
                    id => "41", nombre => "5 – 10 minutos",
                    id => "42", nombre => "0.8 – 2.0 ng /ml",
                    id => "43", nombre => "5.0 – 13.0 ug /dl",
                    id => "44", nombre => "0.4 – 7.0  uUI /ml",
                    id => "45", nombre => "Menor o Igual a 200 UI/L",
                    id => "46", nombre => "Negativo menor de 200 mg /dl ",
                    id => "46", nombre => "Positivo mayor o igual 200 mg/dl",
                    id => "47", nombre => "0.5 – 5.8 UI /mL",
                    id => "48", nombre => "14 semana  23.2",
                    id => "48", nombre => "15 semana  25.6 ",
                    id => "48", nombre => "17 semana  33.5",
                    id => "48", nombre => "18 semana  40.1",
                    id => "48", nombre => "19 semana  45.4",
                    id => "49", nombre => "Menor o igual  6 - 0 mg /dl",
                    id => "50", nombre => "0.02 – 1.35 mg /dl",
                    id => "51", nombre => "Hasta 200 UI / ml",
                    id => "52", nombre => "0.8 – 11.2 mg /dl ",
                    id => "53", nombre => "No reactivo: 0.0 – 0.300",
                    id => "53", nombre => "Débil reactivo: 0.5 <- 1.0 ",
                    id => "53", nombre => "Reactivo: mayor de 1.0",
                    id => "54", nombre => "No reactivo: 0.0 – 0.300",
                    id => "54", nombre => "Débil reactivo: 0.5 <- 1.0",
                    id => "54", nombre => "Reactivo: mayor de 1.0",
                    id => "55", nombre => "Salmonella  typhi   O",
                    id => "55", nombre => "Salmonella  typhi   H",
                    id => "55", nombre => "Salmonella  paratyphi   a",
                    id => "55", nombre => "Salmonella  paratyphi   b",
                    id => "55", nombre => "Brucella  abortus",
                    id => "55", nombre => "Proteus  O X 19 ",
                    id => "56", nombre => "Hasta 35.0 – U/ml",
                    id => "57", nombre => "Negativo < - 0.90 UI /ml",
                    id => "57", nombre => "Positivo > - 1.00 UI/ml",
                    id => "58", nombre => "Negativo < - 0.90 ",
                    id => "58", nombre => "Positivo > - 1.00 ",
                    id => "59", nombre => "Mujeres:  hasta  39 U/L",
                    id => "59", nombre => "Hombres: hasta  66 U/L",
                    id => "60", nombre => "Menor o igual 12 U/mL",
                    id => "61", nombre => "Mujeres 1 – 25 ng /ml",
                    id => "61", nombre => "Hombres 1 – 20 ng /ml ",
                    id => "61", nombre => "3º trimestre de embarazo 95.0 – 473ng/dl",
                    id => "62", nombre => "Niños menores  12 años menor de 10uIu/ml",
                    id => "62", nombre => "Adultos  7 – 9.0uIu /ml",
                    id => "62", nombre => "Paciente diabético   7 – 25uIu /ml",
                    id => "63", nombre => "Negativo ",
                    id => "64", nombre => "Negativo  Menor de 10 GPL",
                    id => "65", nombre => "Negativo  Menor de  5.0 MPL",
                    id => "66", nombre => "2.0 – 4.0 g /L",
                    id => "67", nombre => "600 – 2000 ml /minutos",
                    id => "68", nombre => "Mujeres 88 – 128 ml /minutos ",
                    id => "68", nombre => "Hombres  97 – 137 ml /minutos ",
                    id => "69", nombre => "Hasta 150 I  u /mL",
                    id => "70", nombre => "Negativa",
                    id => "71", nombre => "Negativo  Menor  a 17 U /mL",
                    id => "71", nombre => "Positivo Mayor o igual a 17 U /mL",
                    id => "72", nombre => "Negativo menor de 0.90",
                    id => "72", nombre => "Positivo mayor de 1.0",
                    id => "73", nombre => "Adultos 5 – 23  ug /dL",
                    id => "73", nombre => "Niño 3 – 21 ug /dL",
                    id => "74", nombre => "Adultos menor de 20 mg /L",
                    id => "74", nombre => "Niños de 3 a 5 años   menor de 20 mg /L",
                    id => "75", nombre => "50 – 170 ug /dL",
                    id => "76", nombre => "Hasta 8 – 5 ng /mL",
                    id => "77", nombre => "0 – 5 mIU /mL",
                    id => "77", nombre => "1ª  Semana 5 – 50 mIU /mL",
                    id => "77", nombre => "10ª  Semana  100,000 – 200,000  mIU /mL",
                    id => "78", nombre => "Menor de 125 pg /mL",
                    id => "79", nombre => "Hb,A2-  0.00 – 3.50",
                    id => "79", nombre => "Hb,F - 0.00 – 1.00",
                    id => "79", nombre => "Hb,A – 96.00  - 99.00"
                   );

        for ($i=0; $i < count($ex); $i++) { 
            $examen = new Examen;
            $examen->nombre     = $ex[$i];
            $examen->save();
        }

        // for ($i=0; $i < count($v); $i++) { 
        //     $examenv = new ExamenValor;
        //     $examenv->examen_id = $v[$i]->id;
        //     $examenv->valor     = $v[$i]->nombre;
        //     $examenv->save();
        // }
        foreach ($v as $value) {
            $examenv = new ExamenValor;
            $examenv->examen_id = $value->id;
                    $examenv->valor     = $value->nombre;
            $examenv->save();
        }
    }
     
}